FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /api
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY OrderService.csproj api/
RUN dotnet restore api/OrderService.csproj
COPY . api/
WORKDIR /src/api
RUN dotnet build OrderService.csproj -c Release -o /dist/build

FROM build AS publish
RUN dotnet publish OrderService.csproj -c Release -o /dist/publish

FROM base AS final
COPY --from=publish /dist/publish .
ENTRYPOINT ["dotnet", "OrderService.dll"]
