version: '3.7'

services:
  order-svc:
    image: demo-ms-order-svc
    build:
      context: ./src/OrderService
      dockerfile: Dockerfile.dev
    entrypoint: dockerize -wait tcp://order-db:1433 -timeout 40s ./.docker/entrypoint.sh
    container_name: demo-ms-order-svc
    ports:
      - 5000:80
    networks:
      - default
    volumes:
      - ./src/OrderService:/home/api/src
    depends_on:
      - order-db
  
  order-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: demo-ms-order-db
    user: root
    ports:
      - 1433
    networks:
      - default
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q27w3eX
      - MSSQL_BACKUP_DIR=/var/opt/sqlserver
      - MSSQL_DATA_DIR=/var/opt/sqlserver
      - MSSQL_LOG_DIR=/var/opt/sqlserver
    volumes:
      - order-db:/var/opt/sqlserver

  adminer:
    image: adminer
    container_name: demo-ms-admin-db
    ports:
      - 8080:8080
    networks:
      - default

volumes:
  order-db:
    driver: local
